# Generated by Django 3.2.18 on 2023-04-20 01:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_auto_20230420_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='select1_users',
            field=models.ManyToManyField(blank=True, related_name='selected1_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='select2_users',
            field=models.ManyToManyField(blank=True, related_name='selected2_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
